### ISSUE TITLE
Bug with "The Lost Cities" - NullPointerException - No Sleeping Possible

### ISSUE THREAD

**Issue by RattenDieb** [henkelmax/sleeping-bags#2]
Hey,
finally I made a Bug report for this. I have reported it to The Lost Cities also, several month ago ...

I hope you can figure something out.

Thanks and bye :)

**Bug description**
If the new version (above lostcities-1.16-4.0.3-alpha) of Lost Cities is installed, Sleeping Bags wont work.
Instant there is this error message in the Log:

Error executing task on Server
java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:151)
	at net.minecraft.world.World.func_180495_p(World.java:376)
	at mcjty.lostcities.setup.ForgeEventHandlers.isValidSpawnBed(ForgeEventHandlers.java:195)
	at mcjty.lostcities.setup.ForgeEventHandlers.onPlayerSleepInBedEvent(ForgeEventHandlers.java:299)
	at net.minecraftforge.eventbus.ASMEventHandler_753_ForgeEventHandlers_onPlayerSleepInBedEvent_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2607/1257265172.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerSleepInBed(ForgeEventFactory.java:467)
	at de.maxhenkel.sleepingbags.items.ItemSleepingBag.trySleep(ItemSleepingBag.java:66)
	at de.maxhenkel.sleepingbags.items.ItemSleepingBag.func_77659_a(ItemSleepingBag.java:56)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982)
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31)
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34)
	at net.minecraft.network.PacketThreadUtil$$Lambda$12738/257166268.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$11615/1562275192.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Versions**
- Minecraft version: 1.16.5
- Forge version: latest
- Mod version: latest

**Other mods**
The Lost Cities above lostcities-1.16-4.0.3-alpha

**Comment by henkelmax** [comment]
This is definitely an issue of the lost cities mod.
I created a PR that fixes this issue in their mod.

Next time please note the following things when reporting an issue:

> Forge version: latest
Mod version: latest

Never just write "latest", since versions change a lot.

Please use something like github gist to post logs, as it spams the issue.
